INSERT INTO jobs (url)
VALUES ('https://www.digikey.com/en/products/filter/thyristors/diacs-sidacs/274'),
       ('https://www.digikey.com/en/products/filter/thyristors/scrs/281'),
       ('https://www.digikey.com/en/products/filter/thyristors/scrs-modules/298'),
       ('https://www.digikey.com/en/products/filter/thyristors/triacs/300'),
       ('https://www.digikey.com/en/products/filter/transistors/bipolar-bjt/bipolar-rf-transistors/283'),
       ('https://www.digikey.com/en/products/filter/transistors/bipolar-bjt/bipolar-transistor-arrays/277'),
       ('https://www.digikey.com/en/products/filter/transistors/bipolar-bjt/bipolar-transistor-arrays-pre-biased/293'),
       ('https://www.digikey.com/en/products/filter/transistors/bipolar-bjt/single-bipolar-transistors/276'),
       ('https://www.digikey.com/en/products/filter/transistors/bipolar-bjt/single-pre-biased-bipolar-transistors/292'),
       ('https://www.digikey.com/en/products/filter/transistors/fets-mosfets/fet-mosfet-arrays/289'),
       ('https://www.digikey.com/en/products/filter/transistors/fets-mosfets/rf-fets-mosfets/285'),
       ('https://www.digikey.com/en/products/filter/transistors/fets-mosfets/single-fets-mosfets/278'),
       ('https://www.digikey.com/en/products/filter/transistors/igbts/single-igbts/279'),
       ('https://www.digikey.com/en/products/filter/transistors/igbts/igbt-modules/297'),
       ('https://www.digikey.com/en/products/filter/transistors/igbts/igbt-arrays/291'),
       ('https://www.digikey.com/en/products/filter/transistors/jfets/288'),
       ('https://www.digikey.com/en/products/filter/transistors/programmable-unijunction/290'),
       ('https://www.digikey.com/en/products/filter/transistors/special-purpose/294'),
       ('https://www.digikey.com/en/products/filter/linear/amplifiers/video-amps-and-modules/737'),
       ('https://www.digikey.com/en/products/filter/diodes/rectifiers/diode-arrays/286'),
       ('https://www.digikey.com/en/products/filter/diodes/rectifiers/single-diodes/280'),
       ('https://www.digikey.com/en/products/filter/diodes/rf-diodes/284'),
       ('https://www.digikey.com/en/products/filter/diodes/variable-capacitance-varicaps-varactors/282'),
       ('https://www.digikey.com/en/products/filter/diodes/zener/single-zener-diodes/287'),
       ('https://www.digikey.com/en/products/filter/diodes/zener/zener-diode-arrays/295')